baseURL = "/"
languageCode = "en-us"
title = "k8s-dev"
theme = "hugo-ink"
paginate = 7

copyright = "©Jayesh Kumar Tank. Contact me before publishing this content"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "k8s-dev"

# Number of characters to show in summary.
summaryLength = 30

[params]
	subtitle = "Personal Blog of [Jayesh Kumar Tank](https://www.linkedin.com/in/jayeshtank). \n Opinions mentioned here are personal and not of my employer."

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[author]
  name = "Jayesh Kumar Tank"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/k8s-dev"


[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jayeshtank"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jtankx"

[taxonomies]
   tag = "tags"
